
#For SQLite3 database
#==================

#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3


#For PostgreSQL database
#==================

#   Ensure the pg gem is defined in your Gemfile
#   gem 'pg'
#

# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: ENV['username']
#   host: ENV['host']

# development:
#   <<: *default
#   database: ENV['database']


#For MySQL database
#==================

#   Ensure the mysql2 gem is defined in your Gemfile
#   gem 'mysql2'
#

# default: &default
#   adapter: mysql2
#   database: ENV['database']
#   pool: 5
#   timeout: 5000
#   username: ENV['username']
#   password: ENV['password']

# test:
#   <<: *default
#   database: ENV['database']

# production:
#   <<: *default
#   database: ENV['database']

